Implement get tweet age
spike-force-1-bacon-evaluators/ds-snippets pull request #1
Opened 2017-02-07 15:28 UTC by JVieira13

Just implemented a code (and respective tests) that gives us a tweet age.

2017-02-07 15:30 UTC, m-maga approved these changes

2017-02-07 15:57 UTC, h314to approved these changes
Good job! Good to merge.

2017-02-08 09:12 UTC, alesr reviewed
The file names should start with lowercase letter.
i.e.: `main.py` and `tests.py`.

2017-02-08 09:12 UTC, alesr commented on Main.py
> +
Please remove this extra blank line.

2017-02-08 09:12 UTC, alesr commented on Tests.py
> +
Same here. Please remove this extra blank line.

2017-02-08 09:15 UTC, coppetti requested changes

2017-02-08 09:15 UTC, coppetti commented on Main.py
> +print lastTweet("2-6-2017")
last print could be removed. 
Logic should be coded outside main
file names should start with lowercase in python: main.py
function names are lowercase with _: last_tweet

2017-02-08 09:15 UTC, coppetti commented on Tests.py
> +class testMainMethods(unittest.TestCase):
test_main_methods

2017-02-08 11:26 UTC, merged